micronaut:
  application:
    name: comvida
  server:
    port: 8097
  security:
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
      - access: isAnonymous()
        pattern: /rapidoc/**
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
#tag::security[]
---
#tag::refresh[]
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret:${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
          access-token:
            expiration: 900000
            #end::refresh[]

    jms:
      activemq:
        artemis:
          enabled: true
          connection-string: tcp://localhost:61616
    router:
      static-resources:
        swagger:
          enabled: true
          paths: classpath:META-INF/swagger
          mapping: /swagger/**
        swagger-ui:
          enabled: true
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
        rapidoc:
          enabled: true
          paths: classpath:META-INF/swagger/views/rapidoc
          mapping: /rapidoc/**

datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: NONE
    maximum-pool-size: 50
    minimum-idle: 5

liquibase:
  datasources:
    default:
      enabled: true
      change-log: classpath:db/liquibase-changelog.xml
      drop-first: false

# management endpoints settings
endpoints:
  swagger:
    enabled: true
  all:
    enabled: false
    sensitive: false
  stop:
    enabled: false

# JSON settings
jackson:
  property-naming-strategy: LOWER_CAMEL_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true